name: CI/CD Comaagora API

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar Dependências
        run: |
          PROJECT_PATH=$(find . -name "Comaagora_API.csproj" | head -n 1)
          dotnet restore "$PROJECT_PATH"

      # O LOGIN DEVE VIR ANTES DO BUILD/PUSH
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # BUILD ÚNICO E ORGANIZADO
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          # Contexto agora é a pasta onde está o seu código e o Dockerfile
          context: ./Comaagora_API
          file: ./Comaagora_API/Dockerfile
          push: true
          tags: joaoigorpaulinopinto/comaagora-api:latest

      - name: Deploy no Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'comaagora-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKER_USERNAME }}/comaagora-api:latest'