name: CI/CD Comaagora API

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # 1. Preparar o ambiente .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 2. Restaurar e Rodar (Apontando para o projeto específico)
      - name: Restaurar dependências
        run: dotnet restore Comaagora_API/Comaagora_API.csproj

      - name: Compilar API
        run: dotnet build Comaagora_API/Comaagora_API.csproj --configuration Release --no-restore

      # 3. Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build e Push da Imagem (Contexto ajustado para a pasta da API)
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./Comaagora_API
          file: ./Comaagora_API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/comaagora-api:latest

      # 5. Atualizar o Azure
      - name: Deploy no Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'comaagora-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKER_USERNAME }}/comaagora-api:latest'